/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => AutoHideCursorPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_CURSOR_SETTINGS = {
  movementThreshold: 3,
  delayTime: 500
};
var HIDE_CURSOR_CLASS = "hide-cursor";
var AutoHideCursorPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.isCursorMoving = false;
    this.handleScrollEvent = () => {
      document.body.classList.add(HIDE_CURSOR_CLASS);
      this.isCursorMoving = false;
    };
    this.handleCursorMovement = (evt) => {
      if (this.hasCursorMovementExceededThreshold(evt)) {
        clearTimeout(this.cursorTimeout);
        document.body.classList.remove(HIDE_CURSOR_CLASS);
        this.isCursorMoving = true;
        this.cursorTimeout = setTimeout(() => {
          document.body.classList.add(HIDE_CURSOR_CLASS);
          this.isCursorMoving = false;
        }, this.settings.delayTime);
      }
    };
  }
  async onload() {
    await this.loadUserSettings();
    this.addSettingTab(new AutoHideCursorSettingsTab(this.app, this));
    this.app.workspace.onLayoutReady(() => {
      this.setEventListeners(document.body);
    });
    this.registerEvent(
      this.app.workspace.on("layout-change", () => {
        setTimeout(() => {
          this.setEventListeners(activeDocument.body);
        }, 1e3);
      })
    );
  }
  setEventListeners(targetElement) {
    targetElement.removeEventListener(
      "mousemove",
      this.handleCursorMovement,
      { capture: true }
    );
    targetElement.removeEventListener("scroll", this.handleScrollEvent, {
      capture: true
    });
    this.registerDomEvent(
      targetElement,
      "mousemove",
      this.handleCursorMovement,
      { capture: true }
    );
    this.registerDomEvent(targetElement, "scroll", this.handleScrollEvent, {
      capture: true
    });
  }
  async loadUserSettings() {
    this.settings = {
      ...DEFAULT_CURSOR_SETTINGS,
      ...await this.loadData()
    };
  }
  async saveUserSettings() {
    await this.saveData(this.settings);
    this.setEventListeners();
  }
  hasCursorMovementExceededThreshold(evt) {
    const movementThreshold = this.settings.movementThreshold;
    const deltaX = Math.abs(evt.movementX);
    const deltaY = Math.abs(evt.movementY);
    return deltaX > movementThreshold || deltaY > movementThreshold;
  }
};
var AutoHideCursorSettingsTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Auto Hide Cursor Settings" });
    new import_obsidian.Setting(containerEl).setName("Movement Threshold (px)").setDesc("Minimum distance to show the cursor again").addSlider((slider) => {
      slider.setLimits(0, 10, 1).setValue(this.plugin.settings.movementThreshold).setDynamicTooltip().onChange(async (value) => {
        this.plugin.settings.movementThreshold = value;
        await this.plugin.saveUserSettings();
      });
    });
    new import_obsidian.Setting(containerEl).setName("Hide Delay (ms)").setDesc("Time to hide the cursor after stopping movement").addSlider((slider) => {
      slider.setLimits(200, 1e3, 25).setValue(this.plugin.settings.delayTime).setDynamicTooltip().onChange(async (value) => {
        this.plugin.settings.delayTime = value;
        await this.plugin.saveUserSettings();
      });
    });
  }
};


/* nosourcemap */